services:
    # control access to voting by how many times an IP address has voted
    fansubebooks.security.authorization.voter.vote_voter:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Security\Authorization\Voter\VoteVoter
        arguments: [ @fansubebooks.entity.repository.vote_repository ]
        public: false
        tags:
            - { name: security.voter }

    fansubebooks.security.authorization.voter.flag_voter:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Security\Authorization\Voter\FlagVoter
        arguments: [ @fansubebooks.entity.repository.flag_repository ]
        public: false
        tags:
            - { name: security.voter }
