services:
    # control access to voting by how many times an IP address has voted
    fansubebooks.security.authorization.voter.vote_voter:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Security\Authorization\Voter\VoteVoter
        arguments: [ @fansubebooks.entity.repository.vote_repository ]
        public: false
        tags:
            - { name: security.voter }

    fansubebooks.security.authorization.voter.flag_voter:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Security\Authorization\Voter\FlagVoter
        arguments: [ @fansubebooks.entity.repository.flag_repository ]
        public: false
        tags:
            - { name: security.voter }

    fansubebooks.security.authorization.voter.suggestion_voter:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Security\Authorization\Voter\SuggestionVoter
        arguments: [ @fansubebooks.entity.repository.suggestion_repository ]
        public: false
        tags:
            - { name: security.voter }

    # exception controller
    fansubebooks.controller.exception:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Controller\ExceptionController
        arguments:
            - @fansubebooks.entity.repository.line_repository
            - @twig
            - %kernel.debug%

    # activity aggregator
    fansubebooks.activity.aggregator:
        class: ChaosTangent\FansubEbooks\Bundle\AppBundle\Activity\Aggregator
        arguments:
            - @doctrine.orm.entity_manager
