imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!search"]
        console:
            type:  console
        searches:
            type: stream
            path: "%kernel.logs_dir%/search.log"
            level: info
            channels: ["search"]

parameters:
    router.request_context.host: fansubebooks.chaostangent.com
    router.request_context.scheme: http
