app:
    resource: "@ChaosTangentFansubEbooksAppBundle/Controller"
    type: annotation

quiz:
    resource: "@ChaosTangentFansubEbooksQuizBundle/Controller"
    prefix: /quiz
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
