security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        quiz:
            pattern: ^/quiz
            anonymous: ~

        main:
            pattern: ^/
            security: false


    access_control:
        - { path: ^/quiz/(question|answer), roles: ROLE_QUIZ }
