security:
    erase_credentials: false

    encoders:
        ChaosTangent\FansubEbooks\Bundle\QuizBundle\Entity\User:
            algorithm: plaintext
            ignore_case: true

    providers:
        quiz:
            id: fansubebooks.quiz.repository.user_repository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        quiz:
            pattern: ^/quiz
            anonymous: ~
            provider: quiz
            twitter:
                check_path: quiz_login
                login_path: quiz
                default_target_path: quiz
                always_use_default_target_path: true
                consumer_key: %twitter_quiz.consumer_key%
                consumer_secret: %twitter_quiz.consumer_secret%
            logout:
                path: quiz_logout
                target: quiz

        main:
            pattern: ^/
            security: false


    access_control:
        - { path: ^/quiz/(question|answer), roles: ROLE_QUIZ }
