security:
    providers:
        quiz:
            entity:
                class: ChaosTangent\FansubEbooks\Bundle\QuizBundle\Entity\User
                property: twitterId

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        quiz:
            pattern: ^/quiz
            anonymous: ~
            twitter:
                login_path: quiz_login
                confirm_path: quiz_login_confirm
                consumer_key: %twitter_quiz.consumer_key%
                consumer_secret: %twitter_quiz.consumer_secret%

        main:
            pattern: ^/
            security: false


    access_control:
        - { path: ^/quiz/(question|answer), roles: ROLE_QUIZ }
