services:
    fansubebooks.twitter:
        class: ChaosTangent\FansubEbooks\Twitter\Client
        arguments: [ %twitter% ]

    fansubebooks.entity.repository.vote_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Vote ]

    fansubebooks.entity.repository.flag_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Flag ]
