services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    fansubebooks.twitter:
        class: ChaosTangent\FansubEbooks\Twitter\Client
        arguments: [ %twitter% ]

    fansubebooks.listener.logging_listener:
        class: ChaosTangent\FansubEbooks\EventListener\LoggingListener
        calls:
            - [ setLogger, [ @logger ] ]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: search }

    fansubebooks.serializer.context:
        class: JMS\Serializer\Context
        factory: [ JMS\Serializer\SerializationContext, create ]
        calls:
            - [ setGroups, [ [ 'Default' ] ] ]
            - [ enableMaxDepthChecks, [ 1 ] ]

    fansubebooks.entity.repository.series_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Series ]

    fansubebooks.entity.repository.line_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Line ]

    fansubebooks.entity.repository.vote_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Vote ]

    fansubebooks.entity.repository.flag_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Flag ]

    fansubebooks.entity.repository.suggestion_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Entity\Suggestion ]
