services:
    fansubebooks.quiz.authentication.provider.twitter:
        class: ChaosTangent\FansubEbooks\Bundle\QuizBundle\Security\TwitterAuthenticationProvider
        arguments:
            - ~ # user provider
            - @session
            - ~ # provider id
            - ~ # consumer key
            - ~ # consumer secret

    fansubebooks.quiz.authentication.listener.twitter:
        class: ChaosTangent\FansubEbooks\Bundle\QuizBundle\Security\TwitterAuthenticationListener
        parent: security.authentication.listener.abstract
        abstract: true
