services:
    fansubebooks.quiz.authentication.provider.twitter:
        class: ChaosTangent\FansubEbooks\Bundle\QuizBundle\Security\TwitterAuthenticationProvider
        arguments:
            - ~ # user provider
            - @session
            - ~ # provider id
            - ~ # consumer key
            - ~ # consumer secret

    fansubebooks.quiz.authentication.twitter_entry_point:
        class: Symfony\Component\Security\Http\EntryPoint\FormAuthenticationEntryPoint
        arguments:
            - @http_kernel
            - ~ # http utils
            - ~ # login path

    fansubebooks.quiz.authentication.listener.twitter:
        class: ChaosTangent\FansubEbooks\Bundle\QuizBundle\Security\TwitterAuthenticationListener
        parent: security.authentication.listener.abstract
        abstract: true

    fansubebooks.quiz.repository.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [ ChaosTangent\FansubEbooks\Bundle\QuizBundle\Entity\User ]
